from datetime import datetime


class RecordServiceModel():
    """
    1時刻あたりの観測データ
    """

    def __init__(self, record):
        self.datetime = datetime.strptime(record[0], "%Y-%m-%d %H:%M")
        self.ukb_velocity = record[1]
        self.ukb_sin_direction = record[2]
        self.ukb_cos_direction = record[3]
        self.kix_velocity = record[4]
        self.kix_sin_direction = record[5]
        self.kix_cos_direction = record[6]
        self.tomogashima_velocity = record[7]
        self.tomogashima_sin_direction = record[8]
        self.tomogashima_cos_direction = record[9]
        self.akashi_velocity = record[10]
        self.akashi_sin_direction = record[11]
        self.akashi_cos_direction = record[12]
        self.osaka_velocity = record[13]
        self.osaka_sin_direction = record[14]
        self.osaka_cos_direction = record[15]
        self.temperature = record[16]

        self.fukuiPressure = record[17]
        self.fukuyamaPressure = record[18]
        self.hamadaPressure = record[19]
        self.hikonePressure = record[20]
        self.himejiPressure = record[21]
        self.hiroshimaPressure = record[22]
        self.kobePressure = record[23]
        self.kochiPressure = record[24]
        self.kurePressure = record[25]
        self.kyotoPressure = record[26]
        self.maizuruPressure = record[27]
        self.matsuePressure = record[28]
        self.matsuyamaPressure = record[29]
        self.murotomisakiPressure = record[30]
        self.naraPressure = record[31]
        self.okayamaPressure = record[32]
        self.osakaPressure = record[33]
        self.owasePressure = record[34]
        self.saigoPressure = record[35]
        self.sakaiPressure = record[36]
        self.shimizuPressure = record[37]
        self.shionomisakiPressure = record[38]
        self.sukumoPressure = record[39]
        self.sumotoPressure = record[40]
        self.tadotsuPressure = record[41]
        self.takamatsuPressure = record[42]
        self.tokushimaPressure = record[43]
        self.tottoriPressure = record[44]
        self.toyookaPressure = record[45]
        self.tsuPressure = record[46]
        self.tsurugaPressure = record[47]
        self.tsuyamaPressure = record[48]
        self.uenoPressure = record[49]
        self.uwajimaPressure = record[50]
        self.wakayamaPressure = record[51]
        self.yokkaichiPressure = record[52]
        self.yonagoPressure = record[53]

        self.height = record[54]
        self.period = record[55]
